name: 'Terraform GitOps Pipeline'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Run'
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Жестко передаем файл конфигурации зеркала через переменную окружения
    - name: Terraform Init
      env:
        TF_CLI_CONFIG_FILE: "./terraform.rc"
      run: terraform init -reconfigure

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      env:
        TF_CLI_CONFIG_FILE: "./terraform.rc"
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        TF_CLI_CONFIG_FILE: "./terraform.rc"
      run: terraform apply -auto-approve
