name: 'Terraform GitOps Pipeline'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Run'
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Мы убрали ломающий шаг. Раннер возьмет правильный конфиг из вашей системы.

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
